name: 'Trigger Circleci pipelines'
description: 'Triggers circleci pr nets'
inputs:
  action:  # id of input
    description: 'Pipeline parameter to pass to circleci'
    required: true
  circleci_slug:
    description: 'Slug for the circleci pipeline to trigger'
    required: true
  circle_token:
    description: 'Circleci token'
    required: true
  pull_request:
    description: 'pull request data'
    required: true
outputs:
  status:
    description: "Api call status"
    value: ${{ steps.random-number-generator.outputs.status }}

runs:
  using: "composite"
  steps:
      - run: echo ${{ inputs.pull_request }}
        shell: bash
      - name: Get PR informations
        id: pr_data
        run: |
          echo "::set-output name=branch::${{ fromJson(inputs.pull_request.data).head.ref }}"
          echo "::set-output name=number::${{ fromJson(inputs.pull_request.data).number }}"
        shell: bash
      - run: echo 'hola'
        shell: bash
